version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.121.3
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_node_modules:/home/node/node_modules
      - ./src/projects:/projects #ホストでpermissionsを777にしておく
      - ./public:/public #ホストでpermissionsを777にしておく
    stdin_open: true
    tty: true
    environment:
      n8n_COMMUNITY_NODES_ENABLED: 'true'
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      N8N_RUNNERS_ENABLED: 'true'
      N8N_UNVERIFIED_PACKAGES_ENABLED: 'true'
      NODE_FUNCTION_ALLOW_BUILTIN: '*' # Node.jsの標準ライブラリ（zlib、Buffer）を使用してzipファイルを作成  
      NODE_FUNCTION_ALLOW_EXTERNAL: '*'
      GENERIC_TIMEZONE: 'Asia/Tokyo'
      TZ: 'Asia/Tokyo'
  voice-box:
    image: voicevox/voicevox_engine:nvidia-latest
    ports:
      - 50021:50021
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  n8n_data:
  n8n_node_modules:
  app_node_modules: