services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
  n8n:
    # image: docker.n8n.io/n8nio/n8n:1.121.3
    image: docker.n8n.io/n8nio/n8n:2.2.4
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_node_modules:/home/node/node_modules
      - ./src/projects:/home/node/.n8n-files/projects #ホストでpermissionsを777にしておく
      - ./public:/home/node/.n8n-files/public #ホストでpermissionsを777にしておく
      - ./out:/home/node/.n8n-files/out
    stdin_open: true
    tty: true
    environment:
      n8n_COMMUNITY_NODES_ENABLED: 'true'
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      N8N_RUNNERS_ENABLED: 'true'
      N8N_UNVERIFIED_PACKAGES_ENABLED: 'true'
      NODE_FUNCTION_ALLOW_BUILTIN: '*' # Node.jsの標準ライブラリ（zlib、Buffer）を使用してzipファイルを作成  
      NODE_FUNCTION_ALLOW_EXTERNAL: '*'
      GENERIC_TIMEZONE: 'Asia/Tokyo'
      TZ: 'Asia/Tokyo'
  voicevox:
    build:
      context: .
      dockerfile: docker/voicevox/Dockerfile
    ports:
      - 50021:50021
    volumes:
      # 初期辞書ファイル（読み取り専用）
      - ./voicevox/dict.json:/app/dict.json
    command: ["gosu", "user", "/opt/voicevox_engine/run", "--use_gpu", "--host", "0.0.0.0"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:50021/speakers || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  # python:
  #   build:
  #     dockerfile: docker/python/Dockerfile
  #   user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"
  #   volumes:
  #     - ./python:/app
  #   command: python /app/export_layers.py ${TARGET_FILE:?err}
volumes:
  n8n_data:
  n8n_node_modules:
  app_node_modules: